version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install extension 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      - run:
          name: Install test dependency 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest pytest-cov
      - run:
          name: Test extension
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pytest -v --cov --cov-report html --cov-report xml --junitxml=test-results/flask_cognito_auth_test/results.xml
      - store_artifacts:
          path: htmlcov/
          destination: coverage/html
      - store_artifacts:
          path: coverage.xml
          destination: coverage/coverage.xml
      - store_test_results:
          path: test-results
workflows:
  main:
    jobs:
      - build-and-test